package info.pharos.ly;


public class C_DEF extends Object  {

// static fields
public static final boolean ADValid = true;
public static final int ALIGN_DOWN = 0x4;
public static final int ALIGN_LEFT = 0x1;
public static final int ALIGN_MID = 0x5;
public static final int ALIGN_RIGHT = 0x2;
public static final int ALIGN_UP = 0x3;
public static final int BTN_BUYNOW = 0xc;
public static final int BTN_DASH = 0x2;
public static final int BTN_FULLVERSION = 0xb;
public static final int BTN_JUMP = 0x1;
public static final int BTN_MAYBELATER = 0xd;
public static final int BTN_MORE = 0xa;
public static final int BTN_MUSIC = 0x4;
public static final int BTN_PAUSE = 0x6;
public static final int BTN_PLAY = 0x9;
public static final int BTN_QUIT = 0x8;
public static final int BTN_RESUME = 0x7;
public static final int BTN_SHAKE = 0x5;
public static final int BTN_SOUND = 0x3;
private static final int[] EVTNULL00ACT = new int[20];
public static final int[][] EVTNULLACT;
public static final int EVT_EFFECT = 0x5;
public static final int EVT_EIDOLONA = 0x4;
public static final int EVT_GAMEBTN = 0x2;
public static final int EVT_LAND = 0x1;
public static final int EVT_MAXEFFECT = 0xa;
public static final int EVT_MAXEIDOLONA = 0x2;
public static final int EVT_MAXGAMEBTN = 0x5;
public static final int EVT_MAXLAND = 0x5;
public static final int EVT_MAXOPERATEBTN = 0x2;
public static final int EVT_MAXPROPA = 0x5;
public static final int EVT_NULL = -0x1;
public static final int EVT_OPERATEBTN = 0x3;
public static final int EVT_POWERBALL = 0x6;
public static final int Error = -0x1;
public static final int FadeOutDLY = 0x40;
public static final int ISTOUCH = 0x2;
public static final int LANDDASHSPEEDADJUST = 0x10000;
public static final int LANDDASHSPEEDAREA = 0x80000;
public static final int LANDRUNMAXSPEED = 0x140000;
public static final int LANDRUNMINSPEED = 0xa0000;
public static final int LANDSPEEDADJUST = 0x100;
public static final int MODE_BUY = 0x8;
public static final int MODE_EXIT = 0x7;
public static final int MODE_INIT = 0x1;
public static final int MODE_INITAGAIN = 0x4;
public static final int MODE_LOADRES = 0x3;
public static final int MODE_LOGO = 0x2;
public static final int MODE_MENU = 0x5;
public static final int MODE_NORMAL = 0x6;
public static final int MSG_BTNEXEC = 0xa;
public static final int MSG_EIDOLONPRISE = 0x2c;
public static final int MSG_GETSCORE = 0x2e;
public static final int MSG_MAKEIDOLON = 0x2b;
public static final int MSG_MAKEPOWERBALL = 0x30;
public static final int MSG_MAKEPROPA = 0x29;
public static final int MSG_MODE = 0x1e;
public static final int MSG_OPERATE = 0x28;
public static final int MSG_POWERBALLCLR = 0x31;
public static final int MSG_PROPAPRISE = 0x2a;
public static final int MSG_RETURN = 0x2f;
public static final int MSG_SCENEDASH = 0x2d;
public static final int MSG_STATE = 0x14;
public static final int POS_JUMP_X = 0x28;
public static final int POS_JUMP_Y = 0x3c;
public static final int POS_MUSIC_X = 0x46;
public static final int POS_MUSIC_Y = 0xf0;
public static final int POS_PAUSE_X = 0x12c;
public static final int POS_PAUSE_Y = 0x32;
public static final int POS_QUIT_X = 0x82;
public static final int POS_QUIT_Y = 0xf0;
public static final int POS_RESUME_X = 0xbe;
public static final int POS_RESUME_Y = 0xf0;
public static final int POS_RUSH_X = 0x28;
public static final int POS_RUSH_Y = 0x1a4;
public static final int POS_SHAKE_X = 0x46;
public static final int POS_SHAKE_Y = 0x136;
public static final int POS_SOUND_X = 0x46;
public static final int POS_SOUND_Y = 0xaa;
public static final int[] ResultNUM1TBL = {0x7f0200c2,0x7f0200c3,0x7f0200c4,0x7f0200c5,0x7f0200c6,0x7f0200c7,0x7f0200c8,0x7f0200c9,0x7f0200ca,0x7f0200cb};
public static final int[] ResultNUM2TBL = {0x7f0200cc,0x7f0200cd,0x7f0200ce,0x7f0200cf,0x7f0200d0,0x7f0200d1,0x7f0200d2,0x7f0200d3,0x7f0200d4,0x7f0200d5};
public static final int[] RunLengthNumTBL = {0x7f0200a3,0x7f0200a4,0x7f0200a5,0x7f0200a6,0x7f0200a7,0x7f0200a8,0x7f0200a9,0x7f0200aa,0x7f0200ab,0x7f0200ac};
public static final int SCROFFSET = 0x30;
public static final int SCR_BASEPOINT = 0x0;
public static final int SCR_HIGH = 0x258;
public static final int SCR_SIDE_D = 0x0;
public static final int SCR_SIDE_U = -0x118;
public static final int SCR_WIDTH = 0x258;
public static final int SHOW_OFFSET_X = -0x1e;
public static final int SHOW_OFFSET_Y = 0x0;
public static final int SPD_BLAST = 0x5;
public static final int SPD_EFFECT = 0x6;
public static final int SPD_EIDOLON = 0x3;
public static final int SPD_GAMEBTN = 0x7;
public static final int SPD_INFO = 0x5;
public static final int SPD_LAND = 0x2;
public static final int SPD_OPERATEBTN = 0x5;
public static final int SPD_PAUSESCR = 0x6;
public static final int SPD_PLAYER = 0x4;
public static final int SPD_POWERBALL = 0x5;
public static final int SPD_PROPA = 0x3;
public static final int STATE_EXIT = 0xa;
public static final int STATE_FAIL = 0x9;
public static final int STATE_INIT = 0x1;
public static final int STATE_INITAGAIN = 0x4;
public static final int STATE_LOADSCR = 0x3;
public static final int STATE_LOGO = 0x2;
public static final int STATE_MAKE = 0x5;
public static final int STATE_OVER = 0xd;
public static final int STATE_PASS = 0x8;
public static final int STATE_PAUSE = 0xb;
public static final int STATE_RESET = 0x6;
public static final int STATE_RESULT = 0xc;
public static final int STATE_RUNNING = 0x7;
public static final int STATE_TOBUY = 0xe;
public static final int[] SceSceneTBL = {0x7f0200ef,0x7f0200f0,0x7f0200f1};
public static final int[] TESTNUMTBL = {0x7f02008f,0x7f020090,0x7f020091,0x7f020092,0x7f020093,0x7f020094,0x7f020095,0x7f020096,0x7f020097,0x7f020098,0x7f020099,0x7f02009a,0x7f02009b,0x7f02009c,0x7f02009d,0x7f02009e,0x7f0200a0};
public static final int TOUCHDOWN = 0x4;
public static final int TOUCHMOVE = 0x10;
public static final int TOUCHUP = 0x8;
public static final int TYPELANDA = 0x0;
public static final int TYPELANDB = 0x1;
public static final int TYPELANDC = 0x2;
public static final int TYPELANDD = 0x3;
public static final int TYPELANDE = 0x4;
public static final int TYPELANDF = 0x5;
public static final int TYPELANDG = 0x6;
public static final int TYPELANDH = 0x7;
public static final int TYPELANDI = 0x8;
public static final int TYPELANDJ = 0x9;
public static final int TYPELANDK = 0xa;
public static final int TYPELANDL = 0xb;
public static final int TYPELANDM = 0xc;
public static final int TYPELANDN = 0xd;
public static final int TYPELANDO = 0xe;
public static final int TYPELANDP = 0xf;
public static final int TYPELANDQ = 0x10;
public static final int TYPELANDR = 0x11;
public static final int TYPELANDS = 0x12;
public static final int TYPELANDT = 0x13;
public static final boolean T_PULLLAND = true;
public static final boolean T_PULLSCR = true;
public static final boolean T_SHOWMAPATTR = false;
public static final int VERSION_HIGH = 0x1;
public static final int VERSION_LOW = 0;
// direct methods

static{
	;
	;
	;
	;
	;
	;
	int[][] v0v11 = new int[6][];
	v0v11[0] = info.pharos.ly.C_DEF.EVTNULL00ACT;
	v0v11[1] = info.pharos.ly.C_DEF.EVTNULL00ACT;
	v0v11[2] = info.pharos.ly.C_DEF.EVTNULL00ACT;
	v0v11[3] = info.pharos.ly.C_DEF.EVTNULL00ACT;
	v0v11[4] = info.pharos.ly.C_DEF.EVTNULL00ACT;
	v0v11[5] = info.pharos.ly.C_DEF.EVTNULL00ACT;
	EVTNULLACT = v0v11;
	// op;
	;
	;
	;
	;
	;
}

public C_DEF(){
	super();
}

}